First implem of the lib
Colisweb/JRubysnessHours pull request #2
Opened 2019-04-06 16:19 UTC by FlorianDoublet

2019-04-09 16:37 UTC, tyrcho commented on core/src/test/scala/com/colisweb/jrubysnesshours/core/SegmentsSpec.scala
> +  def aDayAt(day: String, time: String): ZonedDateTime =
pourquoi dans test plutot que main ces méthodes ? elles m'ont l'air bien pratiques

2019-04-09 16:40 UTC, tyrcho commented on core/src/main/scala/com/colisweb/jrubysnesshours/core/Core.scala
>    case class Interval(startTime: LocalTime, endTime: LocalTime)
à défaut de pouvoir utiliser Refined (pas forcément pratique depuis Ruby), je propose de rajouter dans le corps de la classe un `assert(start < end)` pour "fail fast".

2019-04-09 18:28 UTC, FlorianDoublet commented on core/src/test/scala/com/colisweb/jrubysnesshours/core/SegmentsSpec.scala
> +  def aDayAt(day: String, time: String): ZonedDateTime =
j'avoue elle est pratique. C'est Cyril qui a implémenté cette methode, je pense que pour le moment elle n'est utile que depuis les tests mais pourra l'être dans la partie qui communique avec JRuby :)

2019-04-09 18:29 UTC, FlorianDoublet commented on core/src/main/scala/com/colisweb/jrubysnesshours/core/Core.scala
>    case class Interval(startTime: LocalTime, endTime: LocalTime)
J'hésite, on devrait faire ce genre de fail / check ici ou alors plutot dans la partie communiquant avec JRuby ?

2019-04-10 09:11 UTC, tyrcho requested changes

2019-04-10 09:11 UTC, tyrcho commented on core/src/main/scala/com/colisweb/jrubysnesshours/core/Core.scala
> +      .foldLeft(Duration.ZERO)(
j'ai l'impression qu'on gagnerait à imlémenter un Numeric[Duration] pour pouvoir écrire
```
Segments
      .segmentsBetween(planning, planningTimeZone, exceptionSegments)(
        start,
        end
      )
      .map(_.duration)
      .sum
```

avec 

```
case class TimeSegment(date: LocalDate, interval: Interval) {

    def startTime: LocalTime = interval.startTime

    def endTime: LocalTime = interval.endTime

    def duration: Duration = Duration.between(startTime, endTime)
  }
```

2019-04-10 09:11 UTC, tyrcho commented on core/src/main/scala/com/colisweb/jrubysnesshours/core/Core.scala
> +          Duration
Numeric simplifierait aussi bien ici

2019-04-10 09:11 UTC, tyrcho commented on core/src/main/scala/com/colisweb/jrubysnesshours/core/Segments.scala
> +  private[core] def mergeSegments(segments: Seq[TimeSegment]): List[TimeSegment] = {
je propose cette implémentation qui me semble plus performante (évite de parcourir la liste dans le mauvais sens : dropRight très inefficace sur une liste)
```
 private[core] def mergeSegments(
                                   segments: List[TimeSegment]
                                 ): List[TimeSegment] = {
    segments
      .sortBy(_.startTime)
      .foldRight(List.empty[TimeSegment]) {
        case (segment, h :: t) => mergeTwoSegment(segment, h) ::: t
        case (segment, Nil) => List(segment)
      }
  }
```

Note : tests OK

2019-04-10 09:11 UTC, tyrcho commented on core/src/main/scala/com/colisweb/jrubysnesshours/core/Segments.scala
> +  // assuming seg1.startTime is always >= seg2.startTime ( and the same day )
je rajouterais un assert plutot qu'un commentaire

2019-04-10 09:11 UTC, tyrcho commented on core/src/test/scala/com/colisweb/jrubysnesshours/core/SegmentsSpec.scala
> +    ZonedDateTime.parse(s"${day}T$time:00.000+01:00[$zoneId]")
ca me parait dangereux la maniere dont on teste ici. Plus haut on définit une zone sur la TZ de Paris, et ici on a l'air de spécifier en plus GMT+1. Ca risque pas de ne plus marcher lors du passage à l'heure d'hiver ?

2019-04-10 09:11 UTC, tyrcho commented on core/src/test/scala/com/colisweb/jrubysnesshours/core/SegmentsSpec.scala
> +    def toLocalTime: LocalTime = LocalTime.parse(str)
si on ajoute `    def -(to: String): Interval = Interval(str.toLocalTime, to.toLocalTime)`

On peut simplifier tous les tests :
```scala
val planning: BusinessHoursByDayOfWeek = Map(
    MONDAY -> List("09:00" - "19:00"),
    TUESDAY -> List(
      "09:30" - "14:00",
      "15:00" - "19:00"
     ),
// ...
```

2019-04-11 12:01 UTC, guizmaii commented on core/src/main/scala/com/colisweb/jrubysnesshours/core/Core.scala
>    case class Interval(startTime: LocalTime, endTime: LocalTime)
La classe Interval de Threeten extra s'assure de ça : https://www.threeten.org/threeten-extra/apidocs/org.threeten.extra/org/threeten/extra/Interval.html

2019-04-11 12:15 UTC, guizmaii commented on core/src/main/scala/com/colisweb/jrubysnesshours/core/Core.scala
> +      .foldLeft(Duration.ZERO)(
Je suis très d'accord avec ta remarque Michel :)

2019-04-11 12:19 UTC, guizmaii commented on core/src/main/scala/com/colisweb/jrubysnesshours/core/Core.scala
> +      .foldLeft(Duration.ZERO)(
Cependant, `Numeric[Duration]` n'est pas implémentable car il faut implémenter une fonction `override def fromInt(x: Int): Duration`

2019-04-11 16:17 UTC, guizmaii commented on core/src/main/scala/com/colisweb/jrubysnesshours/core/Core.scala
>    case class Interval(startTime: LocalTime, endTime: LocalTime)
Je l'ai fait dans ma PR: https://github.com/Colisweb/JRubysnessHours/pull/5/files#diff-4bd90dcefda7c996d665c7b1c807af8cR56

2019-04-11 16:18 UTC, guizmaii commented on core/src/main/scala/com/colisweb/jrubysnesshours/core/Core.scala
> +      .foldLeft(Duration.ZERO)(
Fait dans ma PR

2019-04-16 07:52 UTC, FlorianDoublet commented on core/src/main/scala/com/colisweb/jrubysnesshours/core/Schedule.scala
> -  def isOpen(instant: ZonedDateTime): Boolean = intervalsBetween(instant, instant).nonEmpty
Pourquoi cette méthode à disparue ? :/

2019-04-17 14:54 UTC, merged